//! Where Desk's assets are, and what is in them.
//!
//! Generated by `node tools/build-desk-assets.mjs`. Do not edit: the hash in
//! each URL is the hash of the file the script wrote, and changing one without
//! the other serves a page that points at nothing.
//!
//! The files' sizes are not published here. The editor bundle publishes its
//! weight because a screen in the product quotes it; Desk has nowhere to show
//! a number, and a constant nothing reads is a fact that stops being true
//! quietly. The script prints them when it runs.

/// The stylesheet's URL.
///
/// Named by [`base.html`](../templates/base.html) and answered by
/// [`crate::routes::stylesheet`]. The hash means a browser may keep it
/// forever, and that a changed stylesheet is a different address rather than a
/// stale copy.
pub const STYLESHEET: &str = "/assets/desk.d1dcc03b05c3.css";

/// The bytes themselves, compiled into the binary.
///
/// Desk is one artefact: copy the binary, run it. A static directory beside it
/// is a second thing to deploy and a second thing to get wrong.
pub const STYLESHEET_CSS: &str = include_str!("../assets/desk.d1dcc03b05c3.css");

/// The script's URL, hashed and cached the same way.
///
/// Everything it does is optional - see `script/desk.js`. A page is complete
/// without it, which is what lets it be loaded `defer` and never waited on.
pub const SCRIPT: &str = "/assets/desk.20559bc1040d.js";

pub const SCRIPT_JS: &str = include_str!("../assets/desk.20559bc1040d.js");
