//! Where Desk's stylesheet is, and what is in it.
//!
//! Generated by `node tools/build-desk-css.mjs`. Do not edit: the hash in the
//! URL is the hash of the file the script wrote, and changing one without the
//! other serves a page that points at nothing.
//!
//! The file's size is not published here. The editor bundle publishes its
//! weight because a screen in the product quotes it; Desk has nowhere to show
//! a number, and a constant nothing reads is a fact that stops being true
//! quietly. The script prints it when it runs.

/// The stylesheet's URL.
///
/// Named by [`base.html`](../templates/base.html) and answered by
/// [`crate::routes::stylesheet`]. The hash means a browser may keep it
/// forever, and that a changed stylesheet is a different address rather than a
/// stale copy.
pub const STYLESHEET: &str = "/assets/desk.9ed4edca5213.css";

/// The bytes themselves, compiled into the binary.
///
/// Desk is one artefact: copy the binary, run it. A static directory beside it
/// is a second thing to deploy and a second thing to get wrong.
pub const STYLESHEET_CSS: &str = include_str!("../assets/desk.9ed4edca5213.css");
