//! Turns `i18n/en.json` into the built-in catalog.
//!
//! # Why generate instead of parsing at runtime
//!
//! The catalog has to exist at *compile* time, because `msg!` checks its key
//! against it and fails the build on a typo. JSON cannot be parsed in a const
//! context, so the file becomes a sorted `&'static [(&str, &str)]` that a const
//! binary search can walk.
//!
//! Generating it also means there is no committed file to drift from the JSON,
//! and no step anybody has to remember to run.
//!
//! # Why English is compiled in rather than loaded
//!
//! It is the floor. Every other language is a deployment file that can be
//! missing, truncated or half-finished, and the answer to any of those has to
//! be readable English rather than a screen of dotted keys. A catalog that is
//! part of the binary cannot fail to load.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set");
    let source = Path::new(&manifest).join("i18n").join("en.json");

    println!("cargo:rerun-if-changed={}", source.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&source)
        .unwrap_or_else(|err| panic!("cannot read {}: {err}", source.display()));

    // A BTreeMap so the output is sorted, which is what lets the const lookup
    // binary-search rather than scan - the check runs once per `msg!` call site
    // and there are a great many of those.
    let parsed: BTreeMap<String, serde_json::Value> = serde_json::from_str(&raw)
        .unwrap_or_else(|err| panic!("{} is not valid JSON: {err}", source.display()));

    let mut entries: Vec<(String, String)> = Vec::with_capacity(parsed.len());

    for (key, value) in parsed {
        // `_comment` and friends document the file for whoever opens it next.
        // They are not translations and must not become keys.
        if key.starts_with('_') {
            continue;
        }

        let serde_json::Value::String(text) = value else {
            panic!("{key} must be a string; nested objects are not a catalog shape");
        };

        if key.trim() != key || key.is_empty() {
            panic!("{key:?} is not a usable key: keys are dotted, trimmed and non-empty");
        }

        entries.push((key, text));
    }

    check_plural_pairs(&entries);

    let mut out = String::with_capacity(entries.len() * 64);
    out.push_str(
        "// Generated by build.rs from i18n/en.json. Do not edit.\n\
         pub static BUILTIN: &[(&str, &str)] = &[\n",
    );

    for (key, text) in &entries {
        // `{:?}` on a `&str` emits a valid Rust string literal, escapes and all,
        // which is exactly what has to land in the generated source.
        out.push_str(&format!("    ({key:?}, {text:?}),\n"));
    }

    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR is always set")).join("builtin.rs");
    fs::write(&dest, out).unwrap_or_else(|err| panic!("cannot write {}: {err}", dest.display()));
}

/// A plural key is a pair or it is a mistake.
///
/// `foo.one` without `foo.other` renders nothing at all for every count but
/// one, and the missing half is invisible until somebody hits that count in
/// production. Cheaper to refuse it here.
fn check_plural_pairs(entries: &[(String, String)]) {
    for (key, _) in entries {
        let Some((stem, form)) = key.rsplit_once('.') else {
            continue;
        };

        let partner = match form {
            "one" => format!("{stem}.other"),
            "other" => format!("{stem}.one"),
            _ => continue,
        };

        if !entries.iter().any(|(candidate, _)| *candidate == partner) {
            panic!("{key} is a plural form with no {partner}");
        }
    }
}
