//! Where an object lives, said in a way that cannot mean anywhere else.
//!
//! A [`StorageKey`] is the only thing any backend is ever asked to store or
//! fetch. It is a slash-separated path whose first segment is always a tenant
//! slug, and every segment of which has been checked - so a key is by
//! construction inside exactly one tenant's area, and cannot climb out of it.
//!
//! ```text
//!   acme/attachments/2026/08/0199c4f2-....pdf
//!   ^^^^ tenant      ^^^^^^^^^^^^^^^^^^^^^^^^ whatever the naming strategy said
//!        ^^^^^^^^^^^ bucket
//! ```
//!
//! # Why this is a type and not a `String`
//!
//! Because a string is validated wherever somebody remembers to validate it,
//! and the cost of forgetting once is a path traversal. Every way of getting a
//! `StorageKey` goes through the same checks, including [`StorageKey::parse`],
//! which is what a key read back out of the database goes through - a row is
//! not more trustworthy than a request, it is only older.
//!
//! # What the checks buy
//!
//! A segment may hold `a-z`, `0-9`, `.`, `-` and `_`, may not begin with `.` or
//! `-`, and may not be `.` or `..`. That is not a style rule:
//!
//! * `..` is the traversal itself.
//! * A leading `.` is a hidden file, and `.git` or `.ssh` inside a storage root
//!   is a directory with meaning to other software.
//! * A leading `-` is a filename that command-line tools read as a flag.
//! * No uppercase, because Windows and Linux disagree about whether `A` and `a`
//!   are the same file, and a key that means two things on two machines is a
//!   key that means nothing.
//!
//! Everything a key is built from is generated by this server - a UUID, a date,
//! a bucket name declared in code - so none of these can be tripped by ordinary
//! use. They exist for the day something else builds a key.

use std::fmt;

use phonix_core::TenantSlug;

/// The directory that holds bytes which have arrived but not yet been checked.
///
/// A sibling of the buckets rather than a bucket, and named with an underscore
/// so it cannot collide with one: bucket names are lowercase letters and
/// hyphens only, enforced by a test in `phonix_core::files::bucket`.
///
/// Its own place because what is in it is, by definition, not yet known to be
/// safe. Nothing serves from here, nothing lists it, and a file that fails
/// verification is deleted from it rather than promoted out of it.
pub const QUARANTINE: &str = "_quarantine";

/// Longest a whole key may be.
///
/// Well inside what any filesystem allows once the storage root is prepended,
/// and short enough that a key fits in an index alongside the rest of a row.
const MAX_KEY_LEN: usize = 400;
const MAX_SEGMENT_LEN: usize = 96;
const MAX_SEGMENTS: usize = 10;

/// A validated location within one tenant's storage.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct StorageKey {
    key: String,
    /// Where the tenant segment ends, so [`StorageKey::tenant`] is a slice
    /// rather than a second parse.
    tenant_len: usize,
}

impl StorageKey {
    /// Build a key inside a tenant's area.
    ///
    /// The tenant is a [`TenantSlug`], not a string, so the first segment is
    /// already known to be one - which is what makes "this key belongs to that
    /// tenant" a property of the type rather than a convention.
    pub fn new<S>(tenant: &TenantSlug, segments: &[S]) -> Result<Self, InvalidStorageKey>
    where
        S: AsRef<str>,
    {
        if segments.is_empty() {
            return Err(InvalidStorageKey::Empty);
        }
        if segments.len() > MAX_SEGMENTS {
            return Err(InvalidStorageKey::TooDeep {
                found: segments.len(),
            });
        }

        let mut key = String::with_capacity(MAX_KEY_LEN.min(64));
        key.push_str(tenant.as_str());
        let tenant_len = key.len();

        for segment in segments {
            let segment = segment.as_ref();
            check_segment(segment)?;
            key.push('/');
            key.push_str(segment);
        }

        if key.len() > MAX_KEY_LEN {
            return Err(InvalidStorageKey::TooLong { found: key.len() });
        }

        Ok(Self { key, tenant_len })
    }

    /// Re-validate a key that came from somewhere else - a database row, a
    /// message payload, an operator's console.
    ///
    /// Deliberately as strict as [`StorageKey::new`]. A key stored last year by
    /// a version of this code with a looser rule is a key this version will
    /// refuse to open, and that is the correct outcome: the alternative is a
    /// path built from data, which is the thing being prevented.
    pub fn parse(raw: &str) -> Result<Self, InvalidStorageKey> {
        let mut parts = raw.split('/');

        let tenant = parts.next().ok_or(InvalidStorageKey::Empty)?;
        let tenant = TenantSlug::parse(tenant).map_err(|_| InvalidStorageKey::Tenant)?;

        // Collected so the count is checked before anything is built, and so a
        // trailing slash shows up as an empty segment rather than being ignored.
        let segments: Vec<&str> = parts.collect();
        Self::new(&tenant, &segments)
    }

    /// Re-validate a key **and** check it belongs to the tenant asking for it.
    ///
    /// The one to use when a key has come out of a database row, which is every
    /// time a file is downloaded or deleted. [`StorageKey::parse`] cannot make
    /// this check for you, and the reason is worth stating plainly: the first
    /// segment of a key is a tenant slug, and *any valid slug* is a valid first
    /// segment. `attachments/report.pdf` parses cleanly - as a key belonging to
    /// a tenant called `attachments`.
    ///
    /// So parsing establishes that a key is well-formed and inside *some*
    /// tenant's area. Establishing that it is inside *this* tenant's area needs
    /// the tenant, and that is this function. A row in Acme's database naming
    /// `globex/attachments/x.pdf` is a bug or an attack; either way it must not
    /// open Globex's file.
    pub fn parse_for(tenant: &TenantSlug, raw: &str) -> Result<Self, InvalidStorageKey> {
        let key = Self::parse(raw)?;

        if key.tenant() != tenant.as_str() {
            return Err(InvalidStorageKey::TenantMismatch {
                expected: tenant.as_str().to_owned(),
                found: key.tenant().to_owned(),
            });
        }

        Ok(key)
    }

    pub fn as_str(&self) -> &str {
        &self.key
    }

    /// The tenant this key belongs to.
    pub fn tenant(&self) -> &str {
        self.key.get(..self.tenant_len).unwrap_or(&self.key)
    }

    /// Everything below the tenant, as separate segments.
    pub fn segments(&self) -> impl Iterator<Item = &str> {
        self.key
            .get(self.tenant_len.saturating_add(1)..)
            .unwrap_or_default()
            .split('/')
    }

    /// The last segment - the file name a backend would write.
    pub fn file_name(&self) -> &str {
        self.key.rsplit('/').next().unwrap_or(&self.key)
    }

    /// Whether this key points into the quarantine area.
    ///
    /// What the download path checks before it serves anything: an object in
    /// quarantine has not been verified, and the difference between "stored"
    /// and "arrived" is the whole of this feature's safety.
    pub fn is_quarantine(&self) -> bool {
        self.segments().next() == Some(QUARANTINE)
    }

    /// The same object under a different name, keeping the tenant.
    ///
    /// How a verified file leaves quarantine: the bytes do not move between
    /// tenants, only between areas, and building the destination this way makes
    /// that structural rather than something a caller must remember.
    pub fn sibling<S>(&self, segments: &[S]) -> Result<Self, InvalidStorageKey>
    where
        S: AsRef<str>,
    {
        let tenant = TenantSlug::parse(self.tenant()).map_err(|_| InvalidStorageKey::Tenant)?;
        Self::new(&tenant, segments)
    }
}

impl fmt::Display for StorageKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.key)
    }
}

impl AsRef<str> for StorageKey {
    fn as_ref(&self) -> &str {
        &self.key
    }
}

/// One segment's rules. See the module docs for why each of these is here.
fn check_segment(segment: &str) -> Result<(), InvalidStorageKey> {
    if segment.is_empty() {
        return Err(InvalidStorageKey::EmptySegment);
    }
    if segment.len() > MAX_SEGMENT_LEN {
        return Err(InvalidStorageKey::SegmentTooLong {
            segment: segment.to_owned(),
        });
    }
    if segment == "." || segment == ".." {
        return Err(InvalidStorageKey::Traversal);
    }
    if segment.starts_with('.') || segment.starts_with('-') {
        return Err(InvalidStorageKey::LeadingCharacter {
            segment: segment.to_owned(),
        });
    }
    if !segment
        .bytes()
        .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || matches!(b, b'.' | b'-' | b'_'))
    {
        return Err(InvalidStorageKey::Charset {
            segment: segment.to_owned(),
        });
    }

    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum InvalidStorageKey {
    #[error("a storage key needs at least one segment below the tenant")]
    Empty,

    #[error("a storage key segment cannot be empty")]
    EmptySegment,

    #[error("the first segment of a storage key must be a valid tenant slug")]
    Tenant,

    #[error("storage key belongs to tenant '{found}', not '{expected}'")]
    TenantMismatch { expected: String, found: String },

    #[error("'.' and '..' are not segments, they are a way out of the storage root")]
    Traversal,

    #[error("segment '{segment}' starts with a character that changes what it means")]
    LeadingCharacter { segment: String },

    #[error("segment '{segment}' contains something other than a-z, 0-9, '.', '-' and '_'")]
    Charset { segment: String },

    #[error("segment '{segment}' is longer than a segment may be")]
    SegmentTooLong { segment: String },

    #[error("a storage key of {found} characters is longer than one may be")]
    TooLong { found: usize },

    #[error("a storage key {found} levels deep is deeper than one may be")]
    TooDeep { found: usize },
}

#[cfg(test)]
mod tests {
    use super::*;

    fn acme() -> TenantSlug {
        TenantSlug::parse("acme").unwrap()
    }

    #[test]
    fn a_key_is_the_tenant_and_then_the_rest() {
        let key = StorageKey::new(&acme(), &["attachments", "2026", "08", "abc.pdf"]).unwrap();

        assert_eq!(key.as_str(), "acme/attachments/2026/08/abc.pdf");
        assert_eq!(key.tenant(), "acme");
        assert_eq!(key.file_name(), "abc.pdf");
        assert_eq!(
            key.segments().collect::<Vec<_>>(),
            vec!["attachments", "2026", "08", "abc.pdf"]
        );
    }

    #[test]
    fn traversal_is_refused_in_every_form_it_arrives_in() {
        for hostile in [
            "..",
            ".",
            "../etc",
            "..\\windows",
            "a/../b",
            "%2e%2e",
            "....//",
        ] {
            assert!(
                StorageKey::new(&acme(), &[hostile]).is_err(),
                "{hostile:?} was accepted as a segment"
            );
        }

        // And through `parse`, which is the path a stored row takes.
        assert!(StorageKey::parse("acme/attachments/../../etc/passwd").is_err());
        assert!(StorageKey::parse("../acme/attachments/x.pdf").is_err());
    }

    #[test]
    fn a_key_cannot_be_built_without_a_tenant() {
        // The type makes this the only shape available: there is no
        // constructor that takes the first segment as a string.
        assert!(StorageKey::parse("/attachments/x.pdf").is_err());
        assert!(StorageKey::parse("").is_err());
        assert!(StorageKey::parse("x/attachments/a.pdf").is_err());
    }

    #[test]
    fn parsing_alone_cannot_tell_whose_key_it_is() {
        // The trap: any valid slug is a valid first segment, so a key with no
        // tenant on the front is indistinguishable from one whose tenant
        // happens to be called "attachments". Parsing accepts it, and is
        // right to.
        let ambiguous = StorageKey::parse("attachments/x.pdf").unwrap();
        assert_eq!(ambiguous.tenant(), "attachments");

        // Which is why anything holding a key from a row asks this instead.
        let acme = acme();
        assert!(StorageKey::parse_for(&acme, "attachments/x.pdf").is_err());
        assert!(StorageKey::parse_for(&acme, "acme/attachments/x.pdf").is_ok());
    }

    #[test]
    fn one_tenants_row_cannot_name_another_tenants_object() {
        let acme = acme();

        match StorageKey::parse_for(&acme, "globex/attachments/secret.pdf") {
            Err(InvalidStorageKey::TenantMismatch { expected, found }) => {
                assert_eq!(expected, "acme");
                assert_eq!(found, "globex");
            }
            other => panic!("a cross-tenant key was accepted: {other:?}"),
        }
    }

    #[test]
    fn a_key_from_a_database_row_is_checked_exactly_like_a_fresh_one() {
        let round_trip = StorageKey::new(&acme(), &["avatars", "2026", "08", "x.png"]).unwrap();
        assert_eq!(StorageKey::parse(round_trip.as_str()).unwrap(), round_trip);

        // A row is older than a request, not more trustworthy than one.
        assert!(StorageKey::parse("acme/avatars/../../../etc/shadow").is_err());
        assert!(StorageKey::parse("acme/avatars//x.png").is_err());
        assert!(StorageKey::parse("acme/avatars/x.png/").is_err());
    }

    #[test]
    fn names_that_mean_something_to_other_software_are_refused() {
        assert!(StorageKey::new(&acme(), &["attachments", ".git"]).is_err());
        assert!(StorageKey::new(&acme(), &["attachments", ".ssh"]).is_err());
        // A tool reading this as a flag rather than a file.
        assert!(StorageKey::new(&acme(), &["attachments", "-rf"]).is_err());
    }

    #[test]
    fn case_is_refused_rather_than_folded() {
        // Folding would mean two keys that are equal on Windows and different
        // on Linux, which is a bug that only appears after deployment.
        assert!(StorageKey::new(&acme(), &["Attachments", "x.pdf"]).is_err());
        assert!(StorageKey::new(&acme(), &["attachments", "X.PDF"]).is_err());
    }

    #[test]
    fn quarantine_is_recognisable_and_cannot_be_a_bucket() {
        let held = StorageKey::new(&acme(), &[QUARANTINE, "0199c4f2.part"]).unwrap();
        assert!(held.is_quarantine());

        let stored = StorageKey::new(&acme(), &["attachments", "x.pdf"]).unwrap();
        assert!(!stored.is_quarantine());

        // Bucket names are letters and hyphens; the underscore is what makes
        // the collision impossible rather than merely unlikely.
        assert!(
            !phonix_core::files::BUCKETS
                .iter()
                .any(|b| b.name == QUARANTINE)
        );
    }

    #[test]
    fn a_sibling_keeps_the_tenant_it_came_from() {
        let held = StorageKey::new(&acme(), &[QUARANTINE, "0199c4f2.part"]).unwrap();
        let promoted = held
            .sibling(&["attachments", "2026", "08", "0199c4f2.pdf"])
            .unwrap();

        assert_eq!(promoted.tenant(), "acme");
        assert!(!promoted.is_quarantine());
        // There is no way to spell a destination in another tenant's area,
        // which is the point of promoting through the key rather than around it.
        assert!(promoted.as_str().starts_with("acme/"));
    }

    #[test]
    fn absurd_keys_are_refused_by_length_as_well_as_by_shape() {
        assert!(StorageKey::new(&acme(), &["a".repeat(200)]).is_err());

        // Deep, but every segment is short and legal - refused on depth alone,
        // because a tree nobody can walk is as much a problem as a long name.
        let deep: Vec<String> = (0..40).map(|n| format!("s{n}")).collect();
        assert!(StorageKey::new(&acme(), &deep).is_err());

        let long: Vec<String> = (0..8).map(|_| "segment".repeat(12)).collect();
        assert!(StorageKey::new(&acme(), &long).is_err());
    }
}
