//! Where the Scalar bundle is, and which one it is.
//!
//! Generated by `node tools/vendor-scalar.mjs`. Do not edit: the hash in the
//! path is the hash of the file the script wrote, and changing one without the
//! other points `/api/v1/docs` at something that is not there.
//!
//! Currently `@scalar/api-reference@1.67.0`: 3650 KiB
//! uncompressed, 1050 KiB on the wire. Facts rather than
//! constants, because nothing in the application needs to branch on them - the
//! numbers are here for whoever is deciding whether to bump the pin.

/// The bundle's URL, relative to the site root.
///
/// Served out of `public/`, which cargo-leptos copies verbatim - the same way
/// the editor bundle is served.
pub const SCALAR_SRC: &str = "/app-assets/scalar.f187dfac27b9.js";
