//! Where the editor bundle is, and what is in it.
//!
//! Generated by `node tools/build-editor.mjs`. Do not edit: the hash in the
//! path is the hash of the file the script wrote, and changing one without the
//! other points the loader at something that is not there.

/// The bundle's URL, relative to the site root.
///
/// Served out of `public/`, which cargo-leptos copies verbatim.
pub const EDITOR_SRC: &str = "/app-assets/editor.90848c771fdf.js";

/// What it weighs uncompressed: 418 KiB.
pub const EDITOR_BYTES: usize = 427913;

/// What it weighs on the wire: 132 KiB.
///
/// The number worth quoting, and the one the interface shows, because the
/// server compresses what it serves - see `phonix_server::startup`. This is
/// what a visitor pays the first time a page has an editor on it.
pub const EDITOR_GZIP_BYTES: usize = 134903;
