/**
 * Bundle `tools/editor/index.js` into a single file the browser can load.
 *
 *     npm install
 *     node tools/build-editor.mjs
 *
 * This runs by hand, not in the build - the same arrangement as
 * `generate-icons.mjs`, and for the same reason. The output is committed, so
 * building and deploying this application needs cargo and nothing else. Node is
 * required only to *change* the editor, which is a deliberate edit by somebody
 * who has already decided to touch JavaScript.
 *
 * # The name carries a hash
 *
 * `public/` is copied to the site root verbatim, and cargo-leptos's `hash-files`
 * covers its own bundle rather than arbitrary assets. An asset served under a
 * name that never changes while its contents do is a browser holding last
 * month's editor - so the content hash is in the filename, and the Rust
 * constant that points at it is generated here at the same moment. The two
 * cannot disagree, because neither is written by hand.
 *
 * A stale editor is a milder illness than a stale wasm bundle - it is mounted
 * imperatively after hydration, so it cannot cause the panic described in
 * `Cargo.toml` - but "the toolbar has a button that does nothing on my machine"
 * is not a bug anybody enjoys.
 */

import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { readdirSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entry = join(root, "tools", "editor", "index.js");
const outDir = join(root, "public", "app-assets");
const constantFile = join(
    root, "crates", "phonix-web", "src", "ui", "editor", "bundle.rs",
);

const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    minify: true,
    // IIFE, not ESM: the file is loaded with a plain `<script src>` appended to
    // the head when the first editor on a page mounts. A module would need
    // either `type="module"` and a different loader, or a dynamic `import()`
    // expression, which is `Function`-shaped and the first thing a strict CSP
    // takes away.
    format: "iife",
    // Roughly "browsers people actually have". ProseMirror does not support
    // anything older, and transpiling further only makes the file bigger.
    target: ["es2020", "chrome100", "firefox100", "safari15"],
    // ProseMirror reads it, and the development build carries warnings that
    // are addressed to somebody writing a plugin.
    define: { "process.env.NODE_ENV": '"production"' },
    legalComments: "none",
    write: false,
});

const [output] = result.outputFiles;
const hash = createHash("sha256").update(output.contents).digest("hex").slice(0, 12);
const name = `editor.${hash}.js`;
// Level 9 because the file is written once and read many times, and because
// it is what a server with compression switched on will end up sending.
const gzipped = gzipSync(output.contents, { level: 9 }).length;

mkdirSync(outDir, { recursive: true });

// Every previous build, removed. Left alone they accumulate one file per edit,
// all of them shipped to the server and none of them reachable.
for (const existing of readdirSync(outDir)) {
    if (/^editor\.[0-9a-f]+\.js$/.test(existing) && existing !== name) {
        rmSync(join(outDir, existing));
        console.log(`  removed ${existing}`);
    }
}

writeFileSync(join(outDir, name), output.contents);

// `\n` explicitly, and no trailing spaces: `.gitattributes` normalises this
// tree to LF, and a generated file that comes back CRLF on a Windows checkout
// is a whole-file diff on every run.
const source = `//! Where the editor bundle is, and what is in it.
//!
//! Generated by \`node tools/build-editor.mjs\`. Do not edit: the hash in the
//! path is the hash of the file the script wrote, and changing one without the
//! other points the loader at something that is not there.

/// The bundle's URL, relative to the site root.
///
/// Served out of \`public/\`, which cargo-leptos copies verbatim.
pub const EDITOR_SRC: &str = "/app-assets/${name}";

/// What it weighs uncompressed: ${(output.contents.length / 1024).toFixed(0)} KiB.
pub const EDITOR_BYTES: usize = ${output.contents.length};

/// What it weighs on the wire: ${(gzipped / 1024).toFixed(0)} KiB.
///
/// The number worth quoting, and the one the interface shows, because the
/// server compresses what it serves - see \`phonix_server::startup\`. This is
/// what a visitor pays the first time a page has an editor on it.
pub const EDITOR_GZIP_BYTES: usize = ${gzipped};
`;

writeFileSync(constantFile, source.replace(/\r\n/g, "\n"));

console.log(`  wrote public/app-assets/${name}`);
console.log(
    `  ${(output.contents.length / 1024).toFixed(1)} KiB uncompressed, ` +
    `${(gzipped / 1024).toFixed(1)} KiB gzipped`,
);
console.log(`  wrote crates/phonix-web/src/ui/editor/bundle.rs`);
