/**
 * Fetch the Scalar API-reference bundle and commit it into `public/`.
 *
 *     node tools/vendor-scalar.mjs
 *
 * Run by hand, like `build-editor.mjs` and `generate-icons.mjs`, and for the
 * same reason: the output is committed, so building and deploying this
 * application needs cargo and nothing else. Node is required only to *change*
 * which Scalar we serve.
 *
 * # Why this is vendored at all
 *
 * `utoipa-scalar`'s default page loads `@scalar/api-reference` from
 * jsdelivr, unpinned. That is two problems on a page we serve to customers:
 * `/api/v1/docs` is blank without internet, and whatever that CDN answers with
 * today executes inside our origin. Neither is acceptable for the page a
 * customer's developer reads before they trust us with their data.
 *
 * So: one pinned version, fetched deliberately, served from the site root by
 * the same static handler that serves the editor. Updating it is an edit to
 * VERSION below and a run of this script - a decision somebody makes, with a
 * diff to review, rather than something that happens overnight.
 *
 * # The name carries a hash
 *
 * Same arrangement as the editor bundle: `public/` is copied to the site root
 * verbatim, so an asset served under a name that never changes while its
 * contents do is a browser holding last month's documentation. The content
 * hash is in the filename and the Rust constant that points at it is written
 * here, at the same moment, so the two cannot disagree.
 */

import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { readdirSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/** Pinned deliberately. Bump it, run this, read the diff. */
const VERSION = "1.67.0";

/**
 * The package's declared browser entrypoint, named in full rather than left to
 * jsdelivr's default-file resolution - which is itself a thing that can change
 * between releases.
 */
const FILE = "dist/browser/standalone.min.js";

const url = `https://cdn.jsdelivr.net/npm/@scalar/api-reference@${VERSION}/${FILE}`;

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "public", "app-assets");
const constantFile = join(
    root, "crates", "phonix-server", "src", "api", "scalar_bundle.rs",
);

console.log(`  fetching ${url}`);

const response = await fetch(url);
if (!response.ok) {
    console.error(`  ${response.status} ${response.statusText}`);
    process.exit(1);
}

const bytes = Buffer.from(await response.arrayBuffer());

// A few hundred kilobytes is the expected shape. A CDN error page dressed as a
// 200 is not, and would otherwise be committed and served as a script.
if (bytes.length < 100_000) {
    console.error(`  ${bytes.length} bytes is too small to be the bundle`);
    process.exit(1);
}

const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 12);
const name = `scalar.${hash}.js`;
const gzipped = gzipSync(bytes, { level: 9 }).length;

mkdirSync(outDir, { recursive: true });

// Every previous version, removed. Left alone they accumulate one file per
// bump, all of them shipped to the server and none of them reachable.
for (const existing of readdirSync(outDir)) {
    if (/^scalar\.[0-9a-f]+\.js$/.test(existing) && existing !== name) {
        rmSync(join(outDir, existing));
        console.log(`  removed ${existing}`);
    }
}

writeFileSync(join(outDir, name), bytes);

// `\n` explicitly, and no trailing spaces: `.gitattributes` normalises this
// tree to LF, and a generated file that comes back CRLF on a Windows checkout
// is a whole-file diff on every run.
const source = `//! Where the Scalar bundle is, and which one it is.
//!
//! Generated by \`node tools/vendor-scalar.mjs\`. Do not edit: the hash in the
//! path is the hash of the file the script wrote, and changing one without the
//! other points \`/api/v1/docs\` at something that is not there.
//!
//! Currently \`@scalar/api-reference@${VERSION}\`: ${(bytes.length / 1024).toFixed(0)} KiB
//! uncompressed, ${(gzipped / 1024).toFixed(0)} KiB on the wire. Facts rather than
//! constants, because nothing in the application needs to branch on them - the
//! numbers are here for whoever is deciding whether to bump the pin.

/// The bundle's URL, relative to the site root.
///
/// Served out of \`public/\`, which cargo-leptos copies verbatim - the same way
/// the editor bundle is served.
pub const SCALAR_SRC: &str = "/app-assets/${name}";
`;

writeFileSync(constantFile, source.replace(/\r\n/g, "\n"));

console.log(`  wrote public/app-assets/${name}`);
console.log(
    `  ${(bytes.length / 1024).toFixed(1)} KiB uncompressed, ` +
    `${(gzipped / 1024).toFixed(1)} KiB gzipped`,
);
console.log(`  wrote crates/phonix-server/src/api/scalar_bundle.rs`);
